version: '3.4'

services:
  nginx-proxy:
    build: .
    image: ${REGISRTY_NAME}devclub-iitd/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - "reverseproxy"
networks:
  reverseproxy:
    external:
      name: "reverseproxy"

