version: '3.4'

services:
  nginx-proxy:
    build: .
    image: ${REGISTRY_NAME}devclub-iitd/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - "reverseproxy"
    restart: always
networks:
  reverseproxy:
    external:
      name: "reverseproxy"

